export const QUESTIONS = [
  // Taylor Swift questions
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift album features the song 'Lover'?",
    answers: [
      { text: "1989", isCorrect: false },
      { text: "Lover", isCorrect: true },
      { text: "Red", isCorrect: false },
      { text: "Reputation", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'lyric',
    question: "Finish the lyric: 'Cause shade never made anybody...'",
    answers: [
      { text: "less gay", isCorrect: true },
      { text: "shine", isCorrect: false },
      { text: "cry", isCorrect: false },
      { text: "smile", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'who',
    question: "Who said: 'You drew stars around my scars'?",
    answers: [
      { text: "Taylor Swift", isCorrect: true },
      { text: "Sabrina Carpenter", isCorrect: false },
      { text: "Selena Gomez", isCorrect: false },
      { text: "Olivia Rodrigo", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song contains the lyric 'I remember it all too well'?",
    answers: [
      { text: "All Too Well", isCorrect: true },
      { text: "Red", isCorrect: false },
      { text: "Enchanted", isCorrect: false },
      { text: "Lover", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'tf',
    question: "True or False: Taylor Swift has an album called 'Midnights'.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift album won Album of the Year at the 2016 Grammys?",
    answers: [
      { text: "1989", isCorrect: true },
      { text: "Red", isCorrect: false },
      { text: "Fearless", isCorrect: false },
      { text: "Lover", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'lyric',
    question: "Finish the lyric: 'We are never ever getting back ...'",
    answers: [
      { text: "together", isCorrect: true },
      { text: "again", isCorrect: false },
      { text: "soon", isCorrect: false },
      { text: "here", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song features the lyric 'Darling I'm a nightmare dressed like a daydream'?",
    answers: [
      { text: "Blank Space", isCorrect: true },
      { text: "Style", isCorrect: false },
      { text: "Bad Blood", isCorrect: false },
      { text: "Wildest Dreams", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which color is most associated with the 'Red' era?",
    answers: [
      { text: "Red", isCorrect: true },
      { text: "Blue", isCorrect: false },
      { text: "Green", isCorrect: false },
      { text: "Gold", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'tf',
    question: "True or False: The lyric 'I shake it off' is from the song 'Shake It Off'.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song is about her relationship with Jake Gyllenhaal?",
    answers: [
      { text: "All Too Well", isCorrect: true },
      { text: "Love Story", isCorrect: false },
      { text: "Style", isCorrect: false },
      { text: "Delicate", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift album is known for its indie-folk sound?",
    answers: [
      { text: "folklore", isCorrect: true },
      { text: "1989", isCorrect: false },
      { text: "Reputation", isCorrect: false },
      { text: "Red", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'tf',
    question: "True or False: Taylor Swift's lucky number is 13.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song features Brendon Urie?",
    answers: [
      { text: "ME!", isCorrect: true },
      { text: "You Need To Calm Down", isCorrect: false },
      { text: "Lover", isCorrect: false },
      { text: "The Man", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'lyric',
    question: "Finish the lyric: 'I knew you were trouble when you ___ in.'",
    answers: [
      { text: "walked", isCorrect: true },
      { text: "came", isCorrect: false },
      { text: "called", isCorrect: false },
      { text: "danced", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song is about a scarf?",
    answers: [
      { text: "All Too Well", isCorrect: true },
      { text: "Cardigan", isCorrect: false },
      { text: "Style", isCorrect: false },
      { text: "The Archer", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'lyric',
    question: "Finish the lyric: 'You can't spell awesome without ___'",
    answers: [
      { text: "me", isCorrect: true },
      { text: "us", isCorrect: false },
      { text: "love", isCorrect: false },
      { text: "fun", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song features the lyric 'Romeo, take me somewhere we can be alone'?",
    answers: [
      { text: "Love Story", isCorrect: true },
      { text: "You Belong With Me", isCorrect: false },
      { text: "Enchanted", isCorrect: false },
      { text: "Fifteen", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'tf',
    question: "True or False: Taylor Swift's first album was self-titled.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song is about a getaway car?",
    answers: [
      { text: "Getaway Car", isCorrect: true },
      { text: "Style", isCorrect: false },
      { text: "Delicate", isCorrect: false },
      { text: "Wildest Dreams", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'lyric',
    question: "Finish the lyric: 'I don't know about you, but I'm feeling ___'",
    answers: [
      { text: "22", isCorrect: true },
      { text: "23", isCorrect: false },
      { text: "18", isCorrect: false },
      { text: "32", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift album features the song 'Cardigan'?",
    answers: [
      { text: "folklore", isCorrect: true },
      { text: "evermore", isCorrect: false },
      { text: "1989", isCorrect: false },
      { text: "Red", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'tf',
    question: "True or False: Taylor Swift has won 3 Album of the Year Grammys.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song features the lyric 'You call me up again just to break me like a promise'?",
    answers: [
      { text: "All Too Well", isCorrect: true },
      { text: "Back to December", isCorrect: false },
      { text: "The Archer", isCorrect: false },
      { text: "Lover", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'lyric',
    question: "Finish the lyric: 'Band-aids don't fix ___'",
    answers: [
      { text: "bullet holes", isCorrect: true },
      { text: "broken hearts", isCorrect: false },
      { text: "scars", isCorrect: false },
      { text: "mistakes", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'mc',
    question: "Which Taylor Swift song is about a love triangle?",
    answers: [
      { text: "betty", isCorrect: true },
      { text: "Lover", isCorrect: false },
      { text: "Style", isCorrect: false },
      { text: "Red", isCorrect: false },
    ],
  },
  {
    artist: 'taylor',
    type: 'tf',
    question: "True or False: Taylor Swift wrote 'This Is What You Came For' for Calvin Harris.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },

  // Sabrina Carpenter questions
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter single went viral on TikTok in 2023?",
    answers: [
      { text: "Nonsense", isCorrect: true },
      { text: "Sue Me", isCorrect: false },
      { text: "Thumbs", isCorrect: false },
      { text: "Skin", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'lyric',
    question: "Finish the lyric: 'I'm so good at ___, I could do it with my eyes closed'",
    answers: [
      { text: "goodbyes", isCorrect: true },
      { text: "lies", isCorrect: false },
      { text: "love", isCorrect: false },
      { text: "games", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter song includes the lyric 'I'm not even half as pretty'?",
    answers: [
      { text: "Because I Liked a Boy", isCorrect: true },
      { text: "Skinny Dipping", isCorrect: false },
      { text: "Sue Me", isCorrect: false },
      { text: "Thumbs", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'tf',
    question: "True or False: Sabrina Carpenter starred in the Disney Channel show 'Girl Meets World'.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which album is the song 'Sue Me' from?",
    answers: [
      { text: "Singular: Act II", isCorrect: true },
      { text: "Singular: Act I", isCorrect: false },
      { text: "Eyes Wide Open", isCorrect: false },
      { text: "Evolution", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'who',
    question: "Who said: 'I want to be remembered for the things I create'?",
    answers: [
      { text: "Sabrina Carpenter", isCorrect: true },
      { text: "Taylor Swift", isCorrect: false },
      { text: "Selena Gomez", isCorrect: false },
      { text: "Billie Eilish", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter song features the lyric 'I can love me better than you can'?",
    answers: [
      { text: "Feather", isCorrect: true },
      { text: "Nonsense", isCorrect: false },
      { text: "Because I Liked a Boy", isCorrect: false },
      { text: "Vicious", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter song is NOT by her?",
    answers: [
      { text: "Enchanted", isCorrect: true },
      { text: "Thumbs", isCorrect: false },
      { text: "Eyes Wide Open", isCorrect: false },
      { text: "Sue Me", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter album features the song 'Paris'?",
    answers: [
      { text: "Singular: Act I", isCorrect: true },
      { text: "Singular: Act II", isCorrect: false },
      { text: "Evolution", isCorrect: false },
      { text: "Eyes Wide Open", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'tf',
    question: "True or False: Sabrina's debut single was 'Can't Blame a Girl for Trying'.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which song did Sabrina release in 2021 that addresses rumors and drama?",
    answers: [
      { text: "Skin", isCorrect: true },
      { text: "Sue Me", isCorrect: false },
      { text: "Thumbs", isCorrect: false },
      { text: "Nonsense", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Disney Channel show did Sabrina star in?",
    answers: [
      { text: "Girl Meets World", isCorrect: true },
      { text: "Liv and Maddie", isCorrect: false },
      { text: "Bizaardvark", isCorrect: false },
      { text: "Jessie", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter song features the lyric 'You got me feeling like a psycho'?",
    answers: [
      { text: "Vicious", isCorrect: true },
      { text: "Feather", isCorrect: false },
      { text: "Skin", isCorrect: false },
      { text: "Sue Me", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'lyric',
    question: "Finish the lyric: 'I got a feeling that it's gonna be a ___ night'",
    answers: [
      { text: "good", isCorrect: true },
      { text: "long", isCorrect: false },
      { text: "crazy", isCorrect: false },
      { text: "fun", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter song features the lyric 'I'm a sucker for the way that you move'?",
    answers: [
      { text: "Almost Love", isCorrect: true },
      { text: "Sue Me", isCorrect: false },
      { text: "Skin", isCorrect: false },
      { text: "Thumbs", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'tf',
    question: "True or False: Sabrina's middle name is Ann.",
    answers: [
      { text: "False", isCorrect: true },
      { text: "True", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter album features the song 'Alien'?",
    answers: [
      { text: "Singular: Act I", isCorrect: false },
      { text: "Singular: Act II", isCorrect: true },
      { text: "Evolution", isCorrect: false },
      { text: "Eyes Wide Open", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'lyric',
    question: "Finish the lyric: 'You can take my youth away, the soul of mine will never break as long as I ___'",
    answers: [
      { text: "wake up", isCorrect: true },
      { text: "stand up", isCorrect: false },
      { text: "dream", isCorrect: false },
      { text: "sing", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter song is about not fitting in?",
    answers: [
      { text: "Thumbs", isCorrect: false },
      { text: "Alien", isCorrect: false },
      { text: "Sue Me", isCorrect: false },
      { text: "Eyes Wide Open", isCorrect: true },
    ],
  },
  {
    artist: 'sabrina',
    type: 'tf',
    question: "True or False: Sabrina Carpenter was born in Pennsylvania.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter song features the lyric 'I hope we both feel the same'?",
    answers: [
      { text: "Paris", isCorrect: false },
      { text: "Sue Me", isCorrect: false },
      { text: "Almost Love", isCorrect: false },
      { text: "Skinny Dipping", isCorrect: true },
    ],
  },
  {
    artist: 'sabrina',
    type: 'lyric',
    question: "Finish the lyric: 'If you want to, you can get to know me again, if you want to, you can ___'",
    answers: [
      { text: "try again", isCorrect: true },
      { text: "call me", isCorrect: false },
      { text: "leave", isCorrect: false },
      { text: "stay", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'mc',
    question: "Which Sabrina Carpenter song is about standing up for yourself?",
    answers: [
      { text: "Sue Me", isCorrect: true },
      { text: "Skin", isCorrect: false },
      { text: "Thumbs", isCorrect: false },
      { text: "Nonsense", isCorrect: false },
    ],
  },
  {
    artist: 'sabrina',
    type: 'tf',
    question: "True or False: Sabrina Carpenter has a sister named Sarah.",
    answers: [
      { text: "True", isCorrect: true },
      { text: "False", isCorrect: false },
    ],
  },
]; 